### ISSUE TITLE
Abgabe Checklist

### ISSUE THREAD

**Issue by Fi0x** [Fi0x/RecipeView#18]
## Zip für Moodle
- [ ] Gesamter Quellcode
- [ ] node_modules Ordner NICHT hinzufügen
- [x] README als Textdatei
- [x] im Readme fehlen noch infos zu den cookies
## Readme
- [ ] Name + Matrikelnummer der Gruppenmitglieder
- [x] URL zur Website
- [x] Fremden Code kennzeichnen
- [x] Beschreibung + Begründung der Architektur
- [x] Beschreibung zum lokalen ausführen der Seite
  - npm install
  - npm run serve
